"""add study log model

Revision ID: baee80779208
Revises: 7f8c3b2fd4a1
Create Date: 2026-02-19 04:31:42.444901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'baee80779208'
down_revision = '7f8c3b2fd4a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('study_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('study_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_study_log_log_date'), ['log_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_study_log_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('study_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_study_log_user_id'))
        batch_op.drop_index(batch_op.f('ix_study_log_log_date'))

    op.drop_table('study_log')
    # ### end Alembic commands ###
